[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.38"
dirs = "5.0.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
toml = "0.8.19"

[lints.clippy]
pedantic = "deny"