[package]
name = "day22ui"
version = "0.1.0"
edition = "2021"

[package.metadata.aoc]
year = 2024
day = 22

[dependencies]
day22 = { path = "../rs" }
ui = { path = "../../common/rs/ui", features = ["wasm-bindgen"]}

[dependencies.yew]
version = "0.21"
features = ["csr"]