[package]
name = "aoc2024-rp-pico2"
version = "0.1.0"
edition = "2024"
authors = ["vescoc"]
homepage = "urn:private"

[dependencies]
cortex-m = "0.7.7"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
rp235x-hal = { version = "0.3.0", features = ["binary-info", "rt", "defmt", "critical-section-impl"] }
usb-device = { version = "0.3.2" }
usbd-serial = "0.2.2"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack400k", "defmt", "blocking"] }
serial-port-splitter = { path = "../../common/serial-port-splitter" }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
