[package]
name = "aoc2024-rp-pico-embassy"
version = "0.1.0"
edition = "2021"
authors = ["vescoc"]
homepage = "urn:private"

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.5"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "nightly"] }
embassy-rp = { version = "0.3.0", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp2040", "binary-info"] }
portable-atomic = { version = "1.10.0", features = ["critical-section"] }
embassy-time = { version = "0.4.0" }
embassy-usb = { version = "0.3.0" }
fugit = { version = "0.3.7", features = ["defmt"] }
static_cell = "2.1.0"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack150k", "defmt", "nonblocking"] }
cdcacm-io = { path = "../../common/cdcacm-io" }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"
large_futures = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
