[package]
name = "esp32c6-embassy"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { version = "0.6.3", features = ["nightly"] }
esp-hal = { version = "0.22.0", features = ["esp32c6"] }
esp-hal-embassy = { version = "0.5.0", features = ["esp32c6"] }
esp-backtrace = { version = "0.14.2", features = ["esp32c6", "exception-handler", "panic-handler", "println"] }
esp-println = { version = "0.12.0", features = ["esp32c6", "log"] }
log = "0.4.22"
fugit = "0.3.7"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack350k", "log", "nonblocking"] }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"
large_futures = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
