[package]
name = "arduino-nano33blesense-embassy"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embedded-io-async = "0.6.1"
embassy-nrf = { version = "0.3.1", features = ["nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "time"] }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "nightly"] }
embassy-time = "0.4.0"
embassy-futures = "0.1.1"
critical-section = "1.2.0"
log = "0.4.24"
fugit = { version = "0.3.7", features = ["defmt"] }
static_cell = "2.1.0"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack150k", "log", "nonblocking"] }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"
large_futures = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'

[profile.dev]
codegen-units = 1
