[package]
name = "esp32c3-embassy"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-hal = { version = "1.0.0-beta.0", features = ["esp32c3", "unstable"] }
embassy-executor = { version = "0.7.0", features = ["nightly"] }
esp-hal-embassy = { version = "0.7.0", features = ["esp32c3"] }
esp-backtrace = { version = "0.15.1", features = ["esp32c3", "exception-handler", "panic-handler", "println"] }
esp-println = { version = "0.13.1", features = ["esp32c3", "log"] }
log = "0.4.22"
fugit = "0.3.7"

embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack250k", "log", "nonblocking"] }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"
large_futures = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
