[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
          "-C", "link-arg=--nmagic",
          "-C", "link-arg=-Tlink.x",
          "-C", "link-arg=-Tdefmt.x",
          "-C", "no-vectorize-loops",
]

[env]
DEFMT_LOG = "debug"