[build]
target = "riscv32imc-unknown-none-elf"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
]

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor -p /dev/ttyUSB0"

[unstable]
build-std = ["core"]

[env]
ESP_LOG = "INFO"