[package]
name = "day15ui"
version = "0.1.0"
edition = "2024"

[dependencies]
day15 = { path = "../rs", default-features = false }
ui = { path = "../../common/rs/ui", features = ["wasm-bindgen"]}

[dependencies.yew]
version = "0.21"
features = ["csr"]