[build]
target = "xtensa-esp32-none-elf"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-nostartfiles",
]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor -p /dev/ttyUSB0"
linker = "/home/pi/.espressif/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc"

[unstable]
build-std = ["core"]

[env]
ESP_LOG = "INFO"