[package]
name = "day03ui"
version = "0.1.0"
edition = "2021"

[dependencies]
day03 = { path = "../rs" }
ui = { path = "../../common/rs/ui", features = ["wasm-bindgen"]}

[dependencies.yew]
version = "0.21"
features = ["csr"]