[package]
name = "nucleo-h743zi"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
stm32h7xx-hal = { version = "0.16.0", features = ["stm32h743v", "defmt", "usb_hs"] }
defmt = "0.3.10"
defmt-rtt = "0.4.1"
usb-device = "0.3.2"
usbd-serial = "0.2.2"
fugit = "0.3.7"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack400k", "defmt", "blocking"] }
serial-port-splitter = { path = "../../common/serial-port-splitter" }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
