[package]
name = "stm32f3discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
stm32f3xx-hal = { version = "0.10.0", features = ["stm32f303xc", "defmt"] }
defmt = "0.3.10"
defmt-rtt = "0.4.1"
fugit = "0.3.7"
usb-device = "0.3.2"
usbd-serial = "0.2.2"
stm32-usbd = "0.7.0"
embedded-time = "0.12.1"
critical-section = "1.2.0"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack3k", "defmt", "blocking"] }
serial-port-splitter = { path = "../../common/serial-port-splitter" }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
