[package]
name = "nucleo-h743zi-embassy"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-stm32 = { version = "0.2.0", features = ["stm32h743zi", "unstable-pac", "memory-x", "time-driver-tim2", "exti"] }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "nightly"] }
embassy-time = "0.4.0"
embassy-usb = "0.4.0"
static_cell = "2.1.0"
defmt = "0.3.10"
defmt-rtt = "0.4.1"
fugit = "0.3.7"
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack400k", "defmt", "nonblocking"] }
cdcacm-io = { path = "../../common/cdcacm-io" }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"
large_futures = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'
