[package]
name = "arduino-nano33blesense"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
nrf52840-hal = "0.18.0"
log = "0.4.24"
embedded-hal = "1.0.0"
embedded-io = "0.6.1"
fugit = { version = "0.3.7", features = ["defmt"] }
embedded-aoc = { path = "../../common/embedded-aoc", default-features = false, features = ["stack150k", "log", "blocking"] }

[lints.clippy]
pedantic = "deny"
large_stack_frames = "deny"

[profile.release]
debug = true
codegen-units = 1
lto = 'fat'

[profile.dev]
codegen-units = 1
