[build]
target = "riscv32imac-unknown-none-elf"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",
#    "-C", "force-frame-pointers",
]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor -p /dev/ttyACM0"

[unstable]
build-std = ["core"]

[env]
ESP_LOG = "INFO"