[package]
name = "day13ui"
version = "0.1.0"
edition = "2021"

[dependencies]
day13 = { path = "../rs", default-features = false }
ui = { path = "../../common/rs/ui", features = ["wasm-bindgen"]}

[dependencies.yew]
version = "0.21"
features = ["csr"]